version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}
    container_name: coffee_fit
    volumes:
      - ./posgress:/var/lib/postgressql/data